apiVersion: v1
kind: Pod
metadata:
 name: samplesecret 
spec:
  containers:
  - name: volumesecret
    image: redis
    volumeMounts:
    - name: sample
      mountPath: "/opt/sample"
      readOnly: true
  volumes:
  - name: sample
    secret:
      secretName: login-cred 
